### ISSUE TITLE
The paste.photos domain would perfectly fit.

### ISSUE THREAD

**Issue by arthurfiorette** [AlejandroAkbal/Paste-Image-to-Download#1]
You should by the paste.photos domain.

https://domains.google.com/registrar/search?searchTerm=paste.photos

**Comment by AlejandroAkbal** [comment]
That is actually a great suggestion :smile:

**Comment by AlejandroAkbal** [comment]
Which one would you prefer? 
1. `paste.photos`
2. `paste.pictures`
3. `paste.pics`

Edit: the other domains are taken

**Comment by AlejandroAkbal** [comment]
Done, it's live at https://www.paste.photos/
